sonar.projectKey=Ovoshchko_DevOps
sonar.organization=ovoshchko
sonar.projectName=DevOps
sonar.projectVersion=1.0

sonar.sources=backend/app,ml-service/app,frontend/src
sonar.tests=backend/tests,ml-service/tests,frontend/tests
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/tests/**

sonar.python.version=3.13
sonar.python.coverage.reportPaths=backend/coverage.xml,ml-service/coverage.xml
sonar.python.xunit.reportPath=*/test-results/pytest.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.testExecutionReportPaths=frontend/test-results/sonar-test-execution.xml
sonar.coverage.exclusions=frontend/src/index.tsx,frontend/src/setupTests.ts,backend/app/repositories/interfaces.py
