from __future__ import annotations

from typing import Protocol

from ..api.schemas.detector import DetectorConfigCreate, DetectorConfigOut, DetectorConfigUpdate
from ..api.schemas.detection import DetectionResult, DetectionRunOut
from ..api.schemas.generator import GeneratorJobCreate, GeneratorJobOut


class DetectorProfileRepository(Protocol):
    def create(self, payload: DetectorConfigCreate) -> DetectorConfigOut: ...
    def list(self) -> list[DetectorConfigOut]: ...
    def get(self, detector_id: str) -> DetectorConfigOut | None: ...
    def update(self, detector_id: str, payload: DetectorConfigUpdate) -> DetectorConfigOut | None: ...
    def delete(self, detector_id: str) -> bool: ...


class DetectionRunRepository(Protocol):
    def save_run(self, run: DetectionRunOut) -> DetectionRunOut: ...
    def save_result(self, result: DetectionResult) -> DetectionResult: ...
    def list_runs(self, detector_profile_id: str | None = None) -> list[DetectionRunOut]: ...
    def get_run(self, detection_id: str) -> DetectionRunOut | None: ...
    def get_results(self, detection_id: str) -> list[DetectionResult]: ...
    def latest_results(self, detector_profile_id: str | None = None, limit: int = 20) -> list[DetectionResult]: ...


class GeneratorJobRepository(Protocol):
    def create(self, payload: GeneratorJobCreate) -> GeneratorJobOut: ...
    def get(self, job_id: str) -> GeneratorJobOut | None: ...
    def update(self, job_id: str, patch: dict) -> GeneratorJobOut | None: ...
