apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ include "traffic-platform.namespace" . }}
  labels:
    {{- include "traffic-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  selector:
    {{- include "traffic-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
  type: {{ .Values.prometheus.service.type }}
