apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: {{ include "traffic-platform.namespace" . }}
  labels:
    {{- include "traffic-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
data:
  DOCKER_INFLUXDB_INIT_MODE: {{ .Values.influxdb.config.mode | quote }}
  DOCKER_INFLUXDB_INIT_ORG: {{ .Values.influxdb.config.org | quote }}
  DOCKER_INFLUXDB_INIT_BUCKET: {{ .Values.influxdb.config.bucket | quote }}
