apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: devops
  labels:
    app: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: ghcr.io/ovoshchko/traffic-ml-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: devops
spec:
  selector:
    app: ml-service
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
