apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: traffic-platform
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: traffic-platform
      useAnnotations: true
