apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

resources:
  - grafana.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-datasources
    files:
      - prometheus.yml=prometheus.yml
  - name: grafana-dashboard-provider
    files:
      - dashboard-provider.yml=dashboard-provider.yml
  - name: grafana-dashboards
    files:
      - traffic-anomaly-platform.json=traffic-anomaly-platform.json
