apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ include "traffic-platform.namespace" . }}
  labels:
    {{- include "traffic-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - {{ .Values.grafana.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
