apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ include "traffic-platform.namespace" . }}
  labels:
    {{- include "traffic-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  selector:
    {{- include "traffic-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: http
  type: {{ .Values.grafana.service.type }}
