apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "traffic-platform.namespace" . }}
  labels:
    {{- include "traffic-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "traffic-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP